### ISSUE TITLE
I got an error saying No such file or directory: 'azcopy': 'azcopy'

### ISSUE THREAD

**Issue by 1069066484** [microsoft/GenerativeImage2Text#1]
### My inference command is:
AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \
"{'type': 'test_git_inference_single_image', \
      'image_path': '/mnt/bd/zhixinling-diffusion/mlx_workspace/3446700194249458680.png', \
      'model_name': 'GIT_BASE', \
      'prefix': '', \
}"

### The whole error traceback is pasted below:
2022-07-17 15:49:41,121.121 122690:inference.py:315   <module>(): param:
{'image_path': '/mnt/bd/zhixinling-diffusion/mlx_workspace/3446700194249458680.png',
 'model_name': 'GIT_BASE',
 'prefix': '',
 'type': 'test_git_inference_single_image'}
/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/torchvision/transforms/transforms.py:333: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
2022-07-17 15:49:51,642.642 122690:cloud_storage.py:952 az_download_once(): if sync, no need to save to temp first
2022-07-17 15:49:51,642.642 122690:common.py:296    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt
2022-07-17 15:49:51,685.685 122690:cloud_storage.py:1013 az_download_once(): ['azcopy',
 'cp',
 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',
 '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']
2022-07-17 15:49:51,685.685 122690:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'azcopy': 'azcopy': tried 1/5-th time
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
    cmd_run(cmd, stdout=stdout)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
    stderr=stderr,
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'
2022-07-17 15:49:53,797.797 122690:cloud_storage.py:952 az_download_once(): if sync, no need to save to temp first
2022-07-17 15:49:53,797.797 122690:common.py:296    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt
2022-07-17 15:49:53,837.837 122690:cloud_storage.py:1013 az_download_once(): ['azcopy',
 'cp',
 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',
 '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']
2022-07-17 15:49:53,837.837 122690:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'azcopy': 'azcopy': tried 2/5-th time
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
    cmd_run(cmd, stdout=stdout)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
    stderr=stderr,
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'
2022-07-17 15:49:57,220.220 122690:cloud_storage.py:952 az_download_once(): if sync, no need to save to temp first
2022-07-17 15:49:57,220.220 122690:common.py:296    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt
2022-07-17 15:49:57,259.259 122690:cloud_storage.py:1013 az_download_once(): ['azcopy',
 'cp',
 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',
 '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']
2022-07-17 15:49:57,259.259 122690:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'azcopy': 'azcopy': tried 3/5-th time
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
    cmd_run(cmd, stdout=stdout)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
    stderr=stderr,
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'
2022-07-17 15:50:02,207.207 122690:cloud_storage.py:952 az_download_once(): if sync, no need to save to temp first
2022-07-17 15:50:02,207.207 122690:common.py:296    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt
2022-07-17 15:50:02,255.255 122690:cloud_storage.py:1013 az_download_once(): ['azcopy',
 'cp',
 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',
 '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']
2022-07-17 15:50:02,255.255 122690:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'azcopy': 'azcopy': tried 4/5-th time
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
    cmd_run(cmd, stdout=stdout)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
    stderr=stderr,
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'
2022-07-17 15:50:06,331.331 122690:cloud_storage.py:952 az_download_once(): if sync, no need to save to temp first
2022-07-17 15:50:06,331.331 122690:common.py:296    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt
2022-07-17 15:50:06,371.371 122690:cloud_storage.py:1013 az_download_once(): ['azcopy',
 'cp',
 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',
 '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']
2022-07-17 15:50:06,372.372 122690:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'azcopy': 'azcopy': tried 5/5-th time
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
    cmd_run(cmd, stdout=stdout)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
    stderr=stderr,
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'
Traceback (most recent call last):
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/bd/zhixinling-diffusion/repos_imagecaption/GenerativeImage2Text/generativeimage2text/inference.py", line 318, in <module>
    locals()[function_name](**kwargs)
  File "/mnt/bd/zhixinling-diffusion/repos_imagecaption/GenerativeImage2Text/generativeimage2text/inference.py", line 81, in test_git_inference_single_image
    checkpoint = torch_load(pretrained)['model']
  File "/mnt/bd/zhixinling-diffusion/repos_imagecaption/GenerativeImage2Text/generativeimage2text/torch_common.py", line 42, in torch_load
    with File.open(filename, 'rb') as fp:
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/azfuse.py", line 50, in open
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 451, in open
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 492, in open_to_read
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 595, in ensure_remote_to_cache
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 571, in remote_to_cache
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 934, in az_download
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 204, in limited_retry_agent
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/cloud_storage.py", line 1011, in az_download_once
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/site-packages/azfuse-0.1-py3.7.egg/azfuse/common.py", line 323, in cmd_run
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/bd/zhixinling-diffusion/envs/miniconda3/envs/GIT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'azcopy': 'azcopy'

**Comment by amsword** [comment]
azcopy should be installed based on the instruction of azfuse.

**Comment by amsword** [comment]
closed as azcopy is missing, based on the instruction of azfuse

**Comment by AyushExel** [comment]
@amsword putting azcopy in the home/code/azcopy/azcopy doesn't work in macos. And copying anything directly in ~/usr/bin requires to reboot system in root mode. Is there an easier way to install this? 
<img width="858" alt="Screenshot 2022-11-16 at 5 49 35 AM" src="https://user-images.githubusercontent.com/15766192/202052532-ea9f2332-cec1-4702-ae52-f5929de45111.png">

I just want to run inference on a local file so is there a way to get rid of azfue requirement ?

**Comment by amsword** [comment]
not "putting azcopy in the home/code/azcopy/azcopy", but "putting azcopy **as** the home/code/azcopy/azcopy". Thus, you should put it in putting azcopy in the home/code/azcopy, not putting azcopy in the home/code/azcopy/azcopy. Can you try this again?

**Comment by AyushExel** [comment]
okay so I tried again. Here is how my home folder(shift + command + H) looks like. The code folder contains azcopy executable as you said. home/code/azcode. I still get the same error
<img width="784" alt="Screenshot 2022-11-16 at 7 17 02 AM" src="https://user-images.githubusercontent.com/15766192/202063163-b947f4e1-4169-4297-aca7-8e88f2c91a75.png">
<img width="1100" alt="Screenshot 2022-11-16 at 7 17 21 AM" src="https://user-images.githubusercontent.com/15766192/202063200-7a5326c4-3eba-40a3-9d92-be325a09cd52.png">

**Comment by AyushExel** [comment]
@amsword 
okay so I tried again. Here is how my home folder(shift + command + H) looks like. The code folder contains azcopy executable as you said. home/code/azcode. I still get the same error <img alt="Screenshot 2022-11-16 at 7 17 02 AM" width="784" src="https://user-images.githubusercontent.com/15766192/202063163-b947f4e1-4169-4297-aca7-8e88f2c91a75.png"> <img alt="Screenshot 2022-11-16 at 7 17 21 AM" width="1100" src="https://user-images.githubusercontent.com/15766192/202063200-7a5326c4-3eba-40a3-9d92-be325a09cd52.png">

**Comment by amsword** [comment]
> @amsword
> okay so I tried again. Here is how my home folder(shift + command + H) looks like. The code folder contains azcopy executable as you said. home/code/azcode. I still get the same error <img alt="Screenshot 2022-11-16 at 7 17 02 AM" width="784" src="https://user-images.githubusercontent.com/15766192/202063163-b947f4e1-4169-4297-aca7-8e88f2c91a75.png"> <img alt="Screenshot 2022-11-16 at 7 17 21 AM" width="1100" src="https://user-images.githubusercontent.com/15766192/202063200-7a5326c4-3eba-40a3-9d92-be325a09cd52.png">

Can you share the result of running the following?
cd
./code/azcopy/azcopy

**Comment by AyushExel** [comment]
@amsword it worked. Thanks so much for your help. 
I'm quite interested in this project and might even contribute a little. I have a few questions. Let me know if I should open new issues for this.
* Does this support cpu/apple silicon? Right now I'm getting an error that "torch isn't compiled with CUDA" after this progess reaches 100%
<img width="713" alt="Screenshot 2022-11-16 at 10 36 21 AM" src="https://user-images.githubusercontent.com/15766192/202088647-8d0fa188-692a-48b2-a411-9cc8285073ef.png">
* How fast are these models on CUDA and CPU? Can we do some optimizations like mixed precision inference etc.?

**Comment by AyushExel** [comment]
opened a PR here for CPU support https://github.com/microsoft/GenerativeImage2Text/pull/26

**Comment by amsword** [comment]
> @amsword it worked. Thanks so much for your help. I'm quite interested in this project and might even contribute a little. I have a few questions. Let me know if I should open new issues for this.
> 
> * Does this support cpu/apple silicon? Right now I'm getting an error that "torch isn't compiled with CUDA" after this progess reaches 100%
> 
> <img alt="Screenshot 2022-11-16 at 10 36 21 AM" width="713" src="https://user-images.githubusercontent.com/15766192/202088647-8d0fa188-692a-48b2-a411-9cc8285073ef.png">
> 
> * How fast are these models on CUDA and CPU? Can we do some optimizations like mixed precision inference etc.?

if you have a cuda device and still hit the issue of 'torch isn't compiled with cuda', one thing you can take a look is the pytorch installation. The cuda version of pytorch might not be compatible.

The inference can also be with fp16 for all parameters. That is, 'model = model.half()' as the model is trained with fp16 with deepspeed. The results should also be similar.
