### ISSUE TITLE
(Windows) ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by Neleac** [microsoft/GenerativeImage2Text#12]
I'm trying to run on Windows and getting a ModuleNotFoundError for `fcntl`, which apparently isn't support on Windows. Does GIT support Windows? Here's my output:

$ AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image',  'image_path': 'aux_data/images/1.jpg', 'model_name': 'GIT_BASE', 'prefix': ''}"
2022-09-18 19:58:30,062.062 39616:inference.py:318   <module>(): param:
{'image_path': 'aux_data/images/1.jpg',
 'model_name': 'GIT_BASE',
 'prefix': '',
 'type': 'test_git_inference_single_image'}
Traceback (most recent call last):
  File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 321, in <module>
    locals()[function_name](**kwargs)
  File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 69, in test_git_inference_single_image
    if File.isfile(f'aux_data/models/{model_name}/parameter.yaml'):
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 39, in isfile
    cls.ensure_initialized()
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 25, in ensure_initialized
    cls.fuser = create_cloud_fuse()
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\cloud_storage.py", line 155, in create_cloud_fuse
    config = load_from_yaml_file(fname)
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 259, in load_from_yaml_file
    with exclusive_open_to_read(file_name, 'r') as fp:
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 108, in exclusive_open_to_read
    lock_fd = acquireLock(op.join('/tmp',
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 181, in acquireLock
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by amsword** [comment]
oh. That is azfuse, which requires that module. One way is 1) manually download the checkpoint to the local folder, 2) disable the azfuse by not enabling it through the environment. Let me know if you need more help on, e.g. how to find out the checkpoint URL.

**Comment by Neleac** [comment]
@amsword I would like to manually download the checkpoint to the local folder. Would you please tell me how to find the checkpoint URL. Thank you!

**Comment by amsword** [comment]
@Neleac  For GIT_BASE, the URL is as follows. For other checkpoints, replace GIT_BASE in the URL. 

https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt

**Comment by Tyrannas** [comment]
I know this issue is now close, but I have the same problem, and I've downloaded the file manually but how do I know in which folder to put it ? Thanks

**Comment by amsword** [comment]
@Tyrannas , If the URL is as follows, the target local file should be `output/GIT_BASE/snapshot/model.pt`. Pay attention to the path at the end of the URLs.

https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt

**Comment by Tyrannas** [comment]
Thanks for your answer, but I'm still facing the problem. (I might be dumb)
I've clone the repo, and put the model.pt in output/GIT_BASE/snapshot/model.pt 
Then i'm trying to run `python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image','image_path': 'C:/path/to/image.jpeg', 'model_name': 'GIT_BASE','prefix': ''}`

**Comment by Neleac** [comment]
@Tyrannas you can dig through the code and comment out the parts that use `fcntl`. Now that you have the model checkpoint file, you can just load it normally using `torch.load('model.pt')`. Or use the solution from [this comment](https://github.com/microsoft/GenerativeImage2Text/issues/6#issuecomment-1251726286).

**Comment by Tyrannas** [comment]
@Neleac  Oh ok thank you very much, it seems to work !
