### ISSUE TITLE
struct Inputs for provisioned git-large-coco fine-tuned model on AWS Sagemaker

### ISSUE THREAD

**Issue by crazyfree** [microsoft/GenerativeImage2Text#51]
Hi, 
I was looking for documents on how to set inputs for model inputs but non of those solutions work. So I have to ask you here in case anyone done this before. 

I deployed the `microsoft/git-large-coco` successfully with script below: 
```
from sagemaker.huggingface import HuggingFaceModel
import sagemaker
import boto3

sess = sagemaker.Session()

# sagemaker session bucket -> used for uploading data, models and logs
# sagemaker will automatically create this bucket if it not exists
sagemaker_session_bucket=None
if sagemaker_session_bucket is None and sess is not None:
    # set to default bucket if a bucket name is not given
    sagemaker_session_bucket = sess.default_bucket()

try:
    role = sagemaker.get_execution_role()
except ValueError as e:
    iam = boto3.client('iam')
    role = iam.get_role(RoleName='sagemaker_execution_role')['Role']['Arn']

# Hub Model configuration. https://huggingface.co/models
hub = {
        'HF_MODEL_ID':'microsoft/git-large-coco',
	'HF_TASK':'image-to-text'
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	transformers_version='4.26.0',
	pytorch_version='1.13.1',
	py_version='py39',
	env=hub,
	role=role, 
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
	initial_instance_count=1, # number of instances
	instance_type='ml.t2.large', # ec2 instance type
        endpoint_name='git-large-coco-inference-endpoint'
)

```

now struggling with model calling. 
```
import boto3
import json

runtime = boto3.Session().client('sagemaker-runtime')
endpoint = 'git-large-coco-inference-endpoint'

response = runtime.invoke_endpoint(EndpointName=endpoint, ContentType='application/json', Body=json.dumps({
        "inputs": {
            "type": "test_git_inference_single_image",
            "image": "https://images.pexels.com/photos/1198172/pexels-photo-1198172.jpeg"
            # 'prefix': 'what is it?', 
        }
    })
)

result = json.loads(response['Body'].read().decode())
print(result)
```

error message: 
```
Traceback (most recent call last):
  File "/Users/leo/Downloads/python_stock_predition/sagemaker/test_sagemaker_endpoint.py", line 47, in <module>
    response = runtime.invoke_endpoint(EndpointName=endpoint, ContentType='application/json', Body=json.dumps({
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{
  "code": 400,
  "type": "InternalServerException",
  "message": "Incorrect format used for image. Should be an url linking to an image, a local path, or a PIL image."
}
". See https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/aws/sagemaker/Endpoints/huggingface-pytorch-git-large-coco-inference in account 711703683918 for more information.
```

please advice on how to solve that issue? 
thanks in advance.

**Comment by amsword** [comment]
this sounds more related to Sagemaker, and you may check if there is any help from there.
